<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\TeamSearcher.Application\TeamSearcher.Application.csproj" />
      <ProjectReference Include="..\TeamSearcher.Domain\TeamSearcher.Domain.csproj" />
    </ItemGroup>

</Project>
