@url = http://localhost:5213

GET {{url}}/api/v1/team/
Accept: application/json

###

GET {{url}}/api/v1/person/
Accept: application/json

###

POST {{url}}/api/v1/person/
Content-Type: application/json

{
    "Name": "Amm",
    "Number": "05734898"
}

###

POST {{url}}/api/v1/team/
Content-Type: application/json

{
    "Name": "abc",
    "CurrentCount": 7,
    "MaxCount": 8,
    "Tag": 2
}